In [9]:
import numpy as np
import cv2
import os

### credit: https://github.com/alishobeiri/Monocular-Video-Odometery
class MonoVideoOdometery(object):
    def __init__(self, 
                img_file_path,
#                 pose_file_path,
                focal_length = 172.98992,
                pp = (163.33639726024606, 134.99537889030861),
                lk_params=dict(winSize  = (21,21),
                               criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 30, 0.01)),
                detector=cv2.FastFeatureDetector_create(threshold=25, nonmaxSuppression=True)):
        '''
        Arguments:
            img_file_path {str} -- File path that leads to image sequences
            pose_file_path {str} -- File path that leads to true poses from image sequence
        
        Keyword Arguments:
            focal_length {float} -- Focal length of camera used in image sequence (default: {718.8560})
            pp {tuple} -- Principal point of camera in image sequence (default: {(607.1928, 185.2157)})
            lk_params {dict} -- Parameters for Lucas Kanade optical flow (default: {dict(winSize  = (21,21), criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 30, 0.01))})
            detector {cv2.FeatureDetector} -- Most types of OpenCV feature detectors (default: {cv2.FastFeatureDetector_create(threshold=25, nonmaxSuppression=True)})
        
        Raises:
            ValueError -- Raised when file either file paths are not correct, or img_file_path is not configured correctly
        '''

        self.file_path = img_file_path
        self.detector = detector
        self.lk_params = lk_params
        self.focal = focal_length
        self.pp = pp
        self.R = np.zeros(shape=(3, 3))
        self.t = np.zeros(shape=(3, 3))
        self.id = 0
        self.n_features = 0
        self.vid_length = len(os.listdir(self.file_path))

        try:
            if not all([".png" in x for x in os.listdir(img_file_path)]):
                raise ValueError("img_file_path is not correct and is not exclusively png files")
        except Exception as e:
            print(e)
            raise ValueError("The designated img_file_path does not exist, please check the path and try again")

#         try:
#             with open(pose_file_path) as f:
#                 self.pose = f.readlines()
#         except Exception as e:
#             print(e)
#             raise ValueError("The pose_file_path is not valid or did not lead to a txt file")
        
        self.process_frame()


    def hasNextFrame(self):
        '''Used to determine whether there are remaining frames
           in the folder to process
        
        Returns:
            bool -- Boolean value denoting whether there are still 
            frames in the folder to process
        '''
    
        return self.id < self.vid_length 


    def detect(self, img):
        '''Used to detect features and parse into useable format
        
        Arguments:
            img {np.ndarray} -- Image for which to detect keypoints on
        
        Returns:
            np.array -- A sequence of points in (x, y) coordinate format
            denoting location of detected keypoint
        '''

        p0 = self.detector.detect(img)
        
        return np.array([x.pt for x in p0], dtype=np.float32).reshape(-1, 1, 2)


    def visual_odometery(self):
        '''
        Used to perform visual odometery. If features fall out of frame
        such that there are less than 2000 features remaining, a new feature
        detection is triggered. 
        '''

        if self.n_features < 2000:
            self.p0 = self.detect(self.old_frame)


        # Calculate optical flow between frames, st holds status
        # of points from frame to frame
        self.p1, st, err = cv2.calcOpticalFlowPyrLK(self.old_frame, 
                                self.current_frame, self.p0, None, **self.lk_params)
        

        # Save the good points from the optical flow
        self.good_old = self.p0[st == 1]
        self.good_new = self.p1[st == 1]


        # If the frame is one of first two, we need to initalize
        # our t and R vectors so behavior is different
        if self.id < 2:
            E, _ = cv2.findEssentialMat(self.good_new, self.good_old, 
                                        self.focal, self.pp, cv2.RANSAC, 0.999, 1.0, None)
            _, self.R, self.t, _ = cv2.recoverPose(E, self.good_old, self.good_new,
                                                   self.R, self.t, self.focal, self.pp, None)
        else:
            E, _ = cv2.findEssentialMat(self.good_new, self.good_old, self.focal, 
                                        self.pp, cv2.RANSAC, 0.999, 1.0, None)
            _, R, t, _ = cv2.recoverPose(E, self.good_old, self.good_new, self.R.copy(), 
                                         self.t.copy(), self.focal, self.pp, None)
            absolute_scale=1
#             absolute_scale = self.get_absolute_scale()
            if (absolute_scale > 0.1 and abs(t[2][0]) > abs(t[0][0]) and abs(t[2][0]) > abs(t[1][0])):
                self.t = self.t + absolute_scale*self.R.dot(t)
                self.R = R.dot(self.R)

        # Save the total number of good features
        self.n_features = self.good_new.shape[0]


    def get_mono_coordinates(self):
        # We multiply by the diagonal matrix to fix our vector
        # onto same coordinate axis as true values
        diag = np.array([[-1, 0, 0],
                        [0, -1, 0],
                        [0, 0, -1]])
        adj_coord = np.matmul(diag, self.t)

        return adj_coord.flatten()


    def get_true_coordinates(self):
        '''Returns true coordinates of vehicle
        
        Returns:
            np.array -- Array in format [x, y, z]
        '''
        return self.true_coord.flatten()


    def get_absolute_scale(self):
        '''Used to provide scale estimation for mutliplying
           translation vectors
        
        Returns:
            float -- Scalar value allowing for scale estimation
        '''
        pose = self.pose[self.id - 1].strip().split()
        x_prev = float(pose[3])
        y_prev = float(pose[7])
        z_prev = float(pose[11])
        pose = self.pose[self.id].strip().split()
        x = float(pose[3])
        y = float(pose[7])
        z = float(pose[11])

        true_vect = np.array([[x], [y], [z]])
        self.true_coord = true_vect
        prev_vect = np.array([[x_prev], [y_prev], [z_prev]])
        
        return np.linalg.norm(true_vect - prev_vect)

    def process_frame(self):
        '''Processes images in sequence frame by frame
        '''

        if self.id < 2:
            self.old_frame = cv2.imread(self.file_path +str().zfill(6)+'.png', 0)
            self.current_frame = cv2.imread(self.file_path + str(1).zfill(6)+'.png', 0)
            self.visual_odometery()
            self.id = 2
        else:
            self.old_frame = self.current_frame
            self.current_frame = cv2.imread(self.file_path + str(self.id).zfill(6)+'.png', 0)
            self.visual_odometery()
            self.id += 1

In [11]:
import cv2 as cv
import matplotlib.pyplot as plt

img_path = 'KITTI/dataset/sequences/00/image_0/'
pose_path = 'KITTI/dataset/poses/00.txt'

focal = 718.8560
pp = (607.1928, 185.2157)
R_total = np.zeros((3, 3))
t_total = np.empty(shape=(3, 1))

# Parameters for lucas kanade optical flow
lk_params = dict( winSize  = (21,21),
                  criteria = (cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 30, 0.01))


# Create some random colors
color = np.random.randint(0,255,(5000,3))

vo = MonoVideoOdometery(img_path, focal, pp, lk_params)
# vo = MonoVideoOdometery(img_path, pose_path, focal, pp, lk_params)
traj = np.zeros(shape=(600, 800, 3))

# mask = np.zeros_like(vo.current_frame)
# flag = False
while(vo.hasNextFrame()):

    frame = vo.current_frame

    # for i, (new,old) in enumerate(zip(vo.good_new, vo.good_old)):
    #     a,b = new.ravel()    
    #     c,d = old.ravel()
        
    #     if np.linalg.norm(new - old) < 10:
    #         if flag:
    #             mask = cv.line(mask, (a,b),(c,d), color[i].tolist(), 2)
    #             frame = cv.circle(frame,(a,b),5,color[i].tolist(),-1)


    # cv.add(frame, mask)
    cv.imshow('frame', frame)
    k = cv.waitKey(1)
    if k == 27:
        break

    if k == 121:
        flag = not flag
        toggle_out = lambda flag: "On" if flag else "Off"
        print("Flow lines turned ", toggle_out(flag))
        mask = np.zeros_like(vo.old_frame)
        mask = np.zeros_like(vo.current_frame)

    vo.process_frame()

    print(vo.get_mono_coordinates())

    mono_coord = vo.get_mono_coordinates()
#     true_coord = vo.get_true_coordinates()

#     print("MSE Error: ", np.linalg.norm(mono_coord - true_coord))
    print("x: {}, y: {}, z: {}".format(*[str(pt) for pt in mono_coord]))
#     print("true_x: {}, true_y: {}, true_z: {}".format(*[str(pt) for pt in true_coord]))

    draw_x, draw_y, draw_z = [int(round(x)) for x in mono_coord]
#     true_x, true_y, true_z = [int(round(x)) for x in true_coord]

#     traj = cv.circle(traj, (true_x + 400, true_z + 100), 1, list((0, 0, 255)), 4)
    traj = cv.circle(traj, (draw_x + 400, draw_z + 100), 1, list((0, 255, 0)), 4)

#     cv.putText(traj, 'Actual Position:', (140, 90), cv.FONT_HERSHEY_SIMPLEX, 0.5,(255,255,255), 1)
    cv.putText(traj, 'Red', (270, 90), cv.FONT_HERSHEY_SIMPLEX, 0.5,(0, 0, 255), 1)
    cv.putText(traj, 'Estimated Odometry Position:', (30, 120), cv.FONT_HERSHEY_SIMPLEX, 0.5,(255,255,255), 1)
    cv.putText(traj, 'Green', (270, 120), cv.FONT_HERSHEY_SIMPLEX, 0.5,(0, 255, 0), 1)

    cv.imshow('trajectory', traj)
cv.imwrite("images/trajectoryK.png", traj)

cv.destroyAllWindows()

[-0.10004014  0.01533944  1.99663934]
x: -0.10004013689904241, y: 0.015339440874482543, z: 1.9966393384358025
[-1.01388115e-01 -1.28492089e-03  2.99650024e+00]
x: -0.10138811487474647, y: -0.0012849208888618142, z: 2.9965002355366632
[-0.12721897 -0.01767062  3.99603226]
x: -0.12721896888242262, y: -0.017670621917911196, z: 3.9960322639294605
[-0.13694784 -0.03193172  4.99588324]
x: -0.13694783583969675, y: -0.03193172007618072, z: 4.995883237938611
[-0.14710626 -0.05068639  5.99565575]
x: -0.1471062599383874, y: -0.050686388165468554, z: 5.9956557464847755
[-0.21312096 -0.06687815  6.99334302]
x: -0.21312096146593354, y: -0.06687815287481123, z: 6.993343015090437
[-0.21733379 -0.07428489  7.99330671]
x: -0.217333794433189, y: -0.07428489091777518, z: 7.9933067105664035
[-0.26208534 -0.10471747  8.99184122]
x: -0.2620853444691331, y: -0.1047174733239631, z: 8.991841215076622
[-0.36363559 -0.09807676  9.98664946]
x: -0.36363558764280673, y: -0.09807675747117534, z: 9.98664946243102
[-0.

[-5.83606272 -0.7634462  78.73566344]
x: -5.836062719457989, y: -0.763446196058164, z: 78.73566344481156
[-5.94758639 -0.77076218 79.72939829]
x: -5.947586385305221, y: -0.7707621810092327, z: 79.72939829290748
[-6.06012287 -0.77354968 80.72304198]
x: -6.060122871353709, y: -0.7735496771368633, z: 80.72304197611247
[-6.15668436 -0.74876566 81.71806038]
x: -6.156684364648337, y: -0.748765661034599, z: 81.71806038325806
[-6.21759739 -0.82774417 82.71307395]
x: -6.217597387915534, y: -0.8277441680422538, z: 82.71307395051596
[-6.33921216 -0.84888363 83.70542619]
x: -6.339212157638479, y: -0.8488836329440151, z: 83.70542619181383
[-6.40549628 -0.84991995 84.70322644]
x: -6.405496283625492, y: -0.8499199484729069, z: 84.70322644271191
[-6.55860035 -0.88477444 85.69082166]
x: -6.558600348201844, y: -0.884774442007819, z: 85.69082165821806
[-6.66619691 -0.88640958 86.68501495]
x: -6.666196908472768, y: -0.8864095774132176, z: 86.6850149525779
[-6.77130563 -0.89956365 87.67938869]
x: -6.771305

[ 44.11954325  -0.60193883 115.10437105]
x: 44.11954325219477, y: -0.6019388315328864, z: 115.10437104706604
[ 45.11532448  -0.57227807 115.1912041 ]
x: 45.11532448292258, y: -0.5722780653863944, z: 115.1912041023031
[ 46.11289782  -0.55512417 115.25868138]
x: 46.11289781895321, y: -0.5551241690637102, z: 115.25868138056532
[ 47.10961152  -0.54662412 115.33923909]
x: 47.109611521038495, y: -0.5466241196901334, z: 115.33923909426231
[ 48.10432272  -0.48677278 115.42271039]
x: 48.104322715201, y: -0.48677278319346806, z: 115.42271039308628
[ 49.10334276  -0.48834659 115.46694234]
x: 49.10334276425556, y: -0.48834659401572, z: 115.46694233523816
[ 50.10191431  -0.47162907 115.51769063]
x: 50.10191431147164, y: -0.47162907410166527, z: 115.51769063194254
[ 51.1007761   -0.49977767 115.55619765]
x: 51.10077609681842, y: -0.49977766612247304, z: 115.5561976513167
[ 52.10016235  -0.51685474 115.58678351]
x: 52.10016234787771, y: -0.5168547442707028, z: 115.58678350745255
[ 53.0993191   -0.497

[ 74.07228936  -0.21611535 133.69334495]
x: 74.0722893623163, y: -0.21611534856758896, z: 133.69334495245553
[ 74.34005096  -0.20769134 134.65679332]
x: 74.34005096100525, y: -0.20769133903677944, z: 134.65679332280598
[ 74.63146382  -0.18101187 135.61301858]
x: 74.6314638210584, y: -0.1810118711544103, z: 135.6130185844411
[ 74.91353041  -0.1532114  136.57201054]
x: 74.91353041096632, y: -0.15321139772490586, z: 136.5720105408906
[ 7.51769935e+01 -1.26353586e-01  1.37536306e+02]
x: 75.17699353269732, y: -0.12635358610126807, z: 137.5363060565094
[ 7.54684344e+01 -9.94334593e-02  1.38492516e+02]
x: 75.46843439099648, y: -0.09943345930833124, z: 138.49251604018835
[ 7.57597828e+01 -1.03108915e-01  1.39449126e+02]
x: 75.75978283411057, y: -0.10310891532032883, z: 139.44912597935797
[ 7.60450421e+01 -9.34113851e-02  1.40407527e+02]
x: 76.04504211343678, y: -0.09341138508590845, z: 140.4075273052469
[ 7.63154871e+01 -7.19609895e-02  1.41370024e+02]
x: 76.31548710279289, y: -0.0719609894803

[ 89.92507892   0.28500559 204.78064092]
x: 89.92507892473522, y: 0.28500559352164573, z: 204.78064092327133
[ 89.99645853   0.2876752  205.77808657]
x: 89.99645852928545, y: 0.2876751951925721, z: 205.7780865735607
[ 90.17368765   0.27692237 206.76219745]
x: 90.17368765393071, y: 0.2769223733046811, z: 206.76219744851275
[ 90.24059803   0.31227891 207.7593298 ]
x: 90.24059802620013, y: 0.31227890969721755, z: 207.7593297955044
[ 90.25901866   0.30712819 208.75914685]
x: 90.25901865541327, y: 0.3071281864220417, z: 208.7591468540052
[ 90.32183962   0.29732372 209.75712351]
x: 90.32183961522021, y: 0.29732371826397774, z: 209.75712350674465
[ 90.32672769   0.29601209 210.7571107 ]
x: 90.32672769324265, y: 0.2960120929421015, z: 210.75711069982876
[ 90.41886081   0.29769445 211.75285598]
x: 90.4188608135667, y: 0.29769444628152936, z: 211.75285597741063
[ 90.46143708   0.29673884 212.75194874]
x: 90.4614370771051, y: 0.2967388439379516, z: 212.75194874017456
[ 90.50927664   0.31660975 21

[8.96010219e+01 1.33315476e-01 2.80683290e+02]
x: 89.60102190258601, y: 0.13331547558689105, z: 280.68328967050536
[8.96097415e+01 1.28856070e-01 2.81683242e+02]
x: 89.60974154659516, y: 0.12885607012603678, z: 281.6832417101109
[8.95909111e+01 1.22711487e-01 2.82683046e+02]
x: 89.59091114925921, y: 0.12271148732259696, z: 282.683045520985
[8.95873350e+01 1.23259083e-01 2.83683039e+02]
x: 89.58733501440543, y: 0.12325908317933923, z: 283.6830389766627
[8.96267159e+01 1.35764942e-01 2.84682185e+02]
x: 89.62671589788819, y: 0.13576494227122424, z: 284.6821849867656
[8.96277562e+01 1.27963604e-01 2.85682154e+02]
x: 89.62775621127172, y: 0.1279636037166085, z: 285.6821540147184
[8.96232752e+01 1.25800644e-01 2.86682142e+02]
x: 89.62327517500887, y: 0.12580064354738385, z: 286.68214163560043
[8.95691519e+01 1.37539004e-01 2.87680607e+02]
x: 89.56915190726714, y: 0.13753900384068352, z: 287.6806068992859
[8.95580534e+01 1.36424899e-01 2.88680545e+02]
x: 89.55805338949023, y: 0.13642489894546

[ 77.3251591    0.83880024 303.09534826]
x: 77.32515909514333, y: 0.8388002358675966, z: 303.09534825762097
[ 76.32869715   0.91896646 303.07010992]
x: 76.32869715290515, y: 0.9189664639407671, z: 303.0701099227426
[ 75.33171642   0.99632209 303.06336276]
x: 75.33171641928969, y: 0.9963220881630215, z: 303.06336276032056
[ 74.33256656   1.03724382 303.06836014]
x: 74.33256656153566, y: 1.037243818026239, z: 303.0683601371415
[ 73.33568028   1.11606361 303.07063596]
x: 73.33568027871817, y: 1.1160636110581506, z: 303.0706359571551
[ 72.33747203   1.17325323 303.08823238]
x: 72.33747202746468, y: 1.1732532334257653, z: 303.0882323835794
[ 71.33904096   1.2284099  303.09788325]
x: 71.33904095677211, y: 1.2284098995577515, z: 303.09788325177215
[ 70.34069896   1.28593419 303.09993479]
x: 70.34069895763986, y: 1.2859341896894698, z: 303.0999347910635
[ 69.34176853   1.33051381 303.11220941]
x: 69.3417685340411, y: 1.3305138095343916, z: 303.1122094113537
[ 68.34428314   1.39045692 303.07439

[  1.65507988   5.88386354 303.56789097]
x: 1.65507988492898, y: 5.88386354067417, z: 303.5678909720273
[  1.65507988   5.88386354 303.56789097]
x: 1.65507988492898, y: 5.88386354067417, z: 303.5678909720273
[  1.65507988   5.88386354 303.56789097]
x: 1.65507988492898, y: 5.88386354067417, z: 303.5678909720273
[  1.65507988   5.88386354 303.56789097]
x: 1.65507988492898, y: 5.88386354067417, z: 303.5678909720273
[  0.75107934   6.11268756 303.92903163]
x: 0.7510793356760241, y: 6.112687556306441, z: 303.92903163274036
[  1.74519318   6.0455533  303.84399833]
x: 1.745193176835893, y: 6.045553301794972, z: 303.8439983293496
[  1.74519318   6.0455533  303.84399833]
x: 1.745193176835893, y: 6.045553301794972, z: 303.8439983293496
[  2.71824753   5.82201119 303.78748154]
x: 2.7182475315879238, y: 5.822011191292724, z: 303.7874815395407
[  2.71824753   5.82201119 303.78748154]
x: 2.7182475315879238, y: 5.822011191292724, z: 303.7874815395407
[  2.05856402   5.59454588 304.50377561]
x: 2.0585

[-19.87300101   8.62579256 339.94504614]
x: -19.873001011970192, y: 8.625792558388031, z: 339.94504613643767
[-19.87225412   8.66855969 340.94413092]
x: -19.872254116468614, y: 8.668559690553987, z: 340.9441309249083
[-19.86115346   8.69567732 341.94370154]
x: -19.861153459171778, y: 8.695677315186233, z: 341.9437015376425
[-19.85420008   8.73720795 342.94281457]
x: -19.85420008350606, y: 8.73720795406115, z: 342.9428145725897
[-19.85002533   8.79749112 343.94098716]
x: -19.850025330770016, y: 8.79749112242084, z: 343.9409871583945
[-19.83936918   8.85079542 344.93950861]
x: -19.83936918128754, y: 8.850795423250235, z: 344.9395086143439
[-19.84375603   8.90701228 345.93791756]
x: -19.843756034777147, y: 8.907012280063197, z: 345.9379175588784
[-19.87732903   8.95553833 346.93617508]
x: -19.87732902964273, y: 8.955538325746913, z: 346.93617507921374
[-19.8511319    9.01784055 347.93388854]
x: -19.85113190346253, y: 9.017840550803424, z: 347.93388853674196
[-19.81034795   9.0347911  348.

[-21.28337289  12.07299011 418.82726218]
x: -21.28337288863811, y: 12.072990110507968, z: 418.82726217747535
[-21.2846456   12.11894414 419.82620492]
x: -21.284645604706387, y: 12.118944137118715, z: 419.8262049223972
[-21.31858318  12.15288175 420.8250525 ]
x: -21.31858317739297, y: 12.15288174849105, z: 420.82505249820366
[-21.3417373   12.18396422 421.8243011 ]
x: -21.34173730110274, y: 12.183964216562917, z: 421.8243010992704
[-21.36717889  12.24074247 422.8223637 ]
x: -21.367178891347297, y: 12.240742472723108, z: 422.82236370006916
[-21.4191972   12.27701117 423.82035101]
x: -21.419197201612576, y: 12.277011171338865, z: 423.8203510130636
[-21.45563037  12.30783783 424.81921153]
x: -21.455630367224, y: 12.307837830139732, z: 424.8192115346334
[-21.48259584  12.34820441 425.81803254]
x: -21.482595835054017, y: 12.348204409869691, z: 425.8180325410132
[-21.54889317  12.38061533 426.81530592]
x: -21.54889317068436, y: 12.38061533492616, z: 426.8153059213986
[-21.57342484  12.4078374

[-36.99719046  14.63445212 443.19290235]
x: -36.997190459802994, y: 14.63445212221463, z: 443.1929023542215
[-37.98289971  14.80126479 443.16943312]
x: -37.98289971224787, y: 14.80126478635421, z: 443.1694331248518
[-38.96795708  14.95496754 443.09173218]
x: -38.96795708400654, y: 14.954967544547658, z: 443.0917321823376
[-39.95784717  15.09029937 443.0492714 ]
x: -39.957847168740024, y: 15.09029936576173, z: 443.04927139674425
[-40.94163762  15.26001881 442.9913779 ]
x: -40.94163762120584, y: 15.260018806000511, z: 442.991377897609
[-41.93207104  15.39741816 443.00414763]
x: -41.93207103675882, y: 15.397418163141918, z: 443.00414762795765
[-42.91998544  15.53651632 443.07253507]
x: -42.91998543645246, y: 15.53651631616989, z: 443.07253507345865
[-43.91175032  15.66458203 443.07127304]
x: -43.911750317558614, y: 15.664582033186429, z: 443.0712730395813
[-44.90161379  15.80416334 443.0450553 ]
x: -44.90161378761015, y: 15.804163338517865, z: 443.0450553001768
[-45.89128586  15.9422274  

[-114.06555161   26.07593692  442.52311987]
x: -114.0655516101355, y: 26.075936924431232, z: 442.5231198686407
[-115.05503873   26.21696082  442.49106529]
x: -115.0550387325055, y: 26.216960819411646, z: 442.49106529473164
[-116.0431635    26.36972433  442.47454996]
x: -116.04316349912561, y: 26.369724327679528, z: 442.4745499644711
[-117.02651083   26.5477006   442.43777387]
x: -117.02651082697011, y: 26.547700595800166, z: 442.43777387431857
[-118.00849764   26.71970567  442.35956808]
x: -118.00849764439539, y: 26.71970566742416, z: 442.3595680833656
[-118.99558603   26.86743384  442.29765765]
x: -118.99558603167276, y: 26.867433844732133, z: 442.2976576534574
[-119.97624934   27.03457114  442.195851  ]
x: -119.97624934353026, y: 27.034571135296385, z: 442.1958509990604
[-120.96297103   27.17950286  442.12253591]
x: -120.96297103332618, y: 27.179502857192638, z: 442.12253590597277
[-121.94889723   27.34019922  442.07642497]
x: -121.9488972281369, y: 27.340199215582416, z: 442.0764249

[-189.9952669    38.23476705  440.63819646]
x: -189.99526690147061, y: 38.23476705051391, z: 440.6381964551342
[-190.98767358   38.35562944  440.6153651 ]
x: -190.98767357791922, y: 38.355629443046354, z: 440.61536510362936
[-191.97973649   38.4675964   440.55814114]
x: -191.97973648847767, y: 38.46759639884332, z: 440.55814113746266
[-192.97228262   38.58088198  440.51321273]
x: -192.97228261624278, y: 38.58088197665584, z: 440.51321272642724
[-193.96049689   38.69486116  440.4110301 ]
x: -193.9604968928184, y: 38.694861158809026, z: 440.4110300977285
[-194.95821116   38.74110282  440.46030436]
x: -194.95821115817432, y: 38.741102822928, z: 440.4603043628658
[-195.94159892   38.89196394  440.3593616 ]
x: -195.9415989161913, y: 38.89196393530369, z: 440.359361596136
[-196.92823476   39.0528206   440.33338384]
x: -196.92823476001206, y: 39.052820604805284, z: 440.3333838447905
[-197.91579306   39.16960391  440.22807351]
x: -197.91579305848552, y: 39.16960390800648, z: 440.22807350717073

[-188.45057688   43.30807574  408.60669395]
x: -188.45057688267872, y: 43.3080757395962, z: 408.6066939546948
[-188.3479157    43.46968513  407.62519353]
x: -188.3479157026341, y: 43.46968512678476, z: 407.6251935277543
[-188.28113041   43.61337422  406.63782674]
x: -188.2811304076223, y: 43.61337422328075, z: 406.63782674285704
[-188.21454984   43.76070491  405.65098294]
x: -188.21454983861852, y: 43.76070491284553, z: 405.6509829377169
[-188.13626466   43.87860301  404.66104785]
x: -188.13626466142935, y: 43.87860301005319, z: 404.6610478541345
[-188.07142186   44.01436512  403.67243061]
x: -188.07142186094813, y: 44.01436512429601, z: 403.6724306078951
[-187.99217427   44.14357313  402.6839848 ]
x: -187.99217426924193, y: 44.14357313468845, z: 402.6839848029775
[-188.00176948   44.27190936  401.69230051]
x: -188.00176948184063, y: 44.271909363762326, z: 401.6923005063375
[-187.98574174   44.41479942  400.70269172]
x: -187.9857417390039, y: 44.41479941726541, z: 400.7026917229946
[-1

[-184.61062219   54.56389297  333.57817864]
x: -184.6106221945087, y: 54.56389297121773, z: 333.5781786449643
[-184.56506685   54.72676781  332.59258416]
x: -184.56506685439084, y: 54.72676780768958, z: 332.5925841550086
[-184.50974799   54.87850917  331.60571315]
x: -184.50974799397565, y: 54.87850916939134, z: 331.60571314883236
[-184.4670842    55.04891899  330.62126392]
x: -184.46708420182944, y: 55.04891899039822, z: 330.62126391512646
[-184.43590248   55.21939199  329.63639506]
x: -184.4359024830351, y: 55.21939198633954, z: 329.63639506189384
[-184.39822367   55.37468609  328.64924561]
x: -184.39822366978737, y: 55.37468609246461, z: 328.6492456063224
[-184.34368114   55.52388805  327.66194429]
x: -184.34368114363755, y: 55.52388804685448, z: 327.66194428977946
[-184.24898563   55.67730953  326.67833125]
x: -184.24898562611023, y: 55.677309526505056, z: 326.6783312517701
[-184.19599489   55.82292763  325.69041053]
x: -184.19599488519466, y: 55.82292763498783, z: 325.690410532350

[-195.70157154   56.37779003  317.57376506]
x: -195.70157154039617, y: 56.377790026209134, z: 317.57376505596073
[-194.71362323   56.53048227  317.54840328]
x: -194.7136232319642, y: 56.53048226682991, z: 317.54840328314106
[-193.72400165   56.67413228  317.54468757]
x: -193.72400165487505, y: 56.67413228480233, z: 317.5446875737723
[-192.73267556   56.80530777  317.55278459]
x: -192.73267555780023, y: 56.80530776893757, z: 317.5527845868177
[-191.74125163   56.93538303  317.54017442]
x: -191.7412516270289, y: 56.93538302828803, z: 317.5401744163653
[-190.75077772   57.06954601  317.50916265]
x: -190.75077771805786, y: 57.069546011899384, z: 317.5091626528538
[-189.76208126   57.21894718  317.52175656]
x: -189.76208126038486, y: 57.21894717669163, z: 317.52175656184124
[-188.77211032   57.36014202  317.51711316]
x: -188.77211032458408, y: 57.36014202479654, z: 317.5171131645567
[-187.78507408   57.51964881  317.53491858]
x: -187.7850740782728, y: 57.51964881399069, z: 317.5349185757762

[-141.07561839   63.49497335  318.10658019]
x: -141.07561839226955, y: 63.49497334554196, z: 318.1065801912966
[-141.95802048   63.38694194  317.64865467]
x: -141.9580204750003, y: 63.38694194239664, z: 317.6486546729785
[-142.83089469   63.28048494  317.17246405]
x: -142.83089469344824, y: 63.28048493841201, z: 317.17246405455825
[-143.64701964   63.15076623  316.60933607]
x: -143.64701963735385, y: 63.150766228551014, z: 316.6093360653346
[-144.44550406   63.03457006  316.01864064]
x: -144.4455040588739, y: 63.03457006305839, z: 316.01864064490667
[-143.6803815    63.10798175  316.65832666]
x: -143.68038150255887, y: 63.10798174647727, z: 316.6583266605077
[-144.3705471    62.9623875   315.94947283]
x: -144.37054710422808, y: 62.96238749655095, z: 315.94947282743567
[-145.05219542   62.83673398  315.22866303]
x: -145.052195418274, y: 62.83673398272687, z: 315.22866302560027
[-145.70872859   62.69819405  314.48719766]
x: -145.70872858742305, y: 62.69819404996449, z: 314.4871976623922


[-102.98136153   71.49838725  332.57910353]
x: -102.98136152649414, y: 71.49838724946778, z: 332.579103531104
[-101.99636844   71.67024374  332.56316709]
x: -101.99636844204836, y: 71.67024374035485, z: 332.563167090662
[-101.01201357   71.83870678  332.61479734]
x: -101.01201356679566, y: 71.83870678308057, z: 332.6147973415019
[-100.02813798   72.0126794   332.65629877]
x: -100.02813798431794, y: 72.0126793952902, z: 332.6562987680442
[-99.04490119  72.19436474 332.67165606]
x: -99.04490119241363, y: 72.19436474003952, z: 332.67165606432394
[-98.06486082  72.3930721  332.67767684]
x: -98.06486081738201, y: 72.39307209650852, z: 332.67767684441844
[-97.08255042  72.57425865 332.72498142]
x: -97.08255042423781, y: 72.57425865430962, z: 332.7249814191764
[-96.10257151  72.75303772 332.81261344]
x: -96.10257150853424, y: 72.7530377168312, z: 332.81261344289106
[-95.11873325  72.92515671 332.86198269]
x: -95.11873324508784, y: 72.92515671304014, z: 332.86198268962187
[-94.13482275  73.103

[-23.94681479  86.18980798 333.27157768]
x: -23.94681479291958, y: 86.18980797841633, z: 333.2715776838099
[-22.99877205  86.3723164  333.0109906 ]
x: -22.998772045805765, y: 86.3723163966738, z: 333.01099060256826
[-22.05937566  86.52668229 332.70487688]
x: -22.05937566341787, y: 86.52668228634863, z: 332.70487688372936
[-21.128686    86.70557353 332.38579277]
x: -21.128685999479075, y: 86.70557352918246, z: 332.38579276836975
[-20.20400152  86.8753023  332.04498379]
x: -20.204001522187088, y: 86.87530230113009, z: 332.04498378751924
[-19.265325    87.09435384 331.77870798]
x: -19.265324997798565, y: 87.09435383711741, z: 331.7787079772333
[-18.33650695  87.36538043 331.52603898]
x: -18.336506950552483, y: 87.36538042627797, z: 331.5260389781892
[-17.45013437  87.6586636  331.16780913]
x: -17.450134370114018, y: 87.65866360211612, z: 331.16780912541714
[-16.58328519  87.86204998 330.71260974]
x: -16.583285188971576, y: 87.86204998453168, z: 330.7126097442658
[-15.65536762  88.10436224

[  0.85736087 101.97855568 271.75721592]
x: 0.8573608715670857, y: 101.978555679995, z: 271.75721592488156
[  0.90958342 102.15809077 270.77485145]
x: 0.9095834222732027, y: 102.15809076947173, z: 270.7748514523744
[  0.95228588 102.3623323  269.79686275]
x: 0.9522858793166328, y: 102.36233230101024, z: 269.79686275256375
[  1.01105391 102.55119837 268.81661996]
x: 1.011053914659618, y: 102.55119837377683, z: 268.8166199639753
[  1.10752793 102.72815402 267.83714078]
x: 1.1075279310062374, y: 102.72815401815856, z: 267.837140783956
[  1.10745174 102.92904326 266.85752682]
x: 1.1074517408113551, y: 102.92904325524006, z: 266.85752682498037
[  1.16563842 103.13081348 265.87982386]
x: 1.16563842453038, y: 103.13081347837968, z: 265.8798238604293
[  1.20897507 103.32333002 264.89948753]
x: 1.2089750705601126, y: 103.32333001658374, z: 264.89948753159683
[  1.27633186 103.49552986 263.91673106]
x: 1.2763318558317258, y: 103.49552986053953, z: 263.91673106266904
[  1.31570018 103.67589405 26

[  4.74390099 115.07026705 201.10314806]
x: 4.743900989970943, y: 115.07026705025648, z: 201.10314806374646
[  4.54079276 114.89084005 202.06572429]
x: 4.540792755775965, y: 114.89084004624814, z: 202.06572429212255
[  4.29389198 114.69981455 203.01575022]
x: 4.293891984417483, y: 114.69981455130228, z: 203.015750223023
[  4.81947149 114.84406684 202.17732464]
x: 4.819471488162389, y: 114.84406683733259, z: 202.17732463704755
[  4.56638006 114.66910199 203.12881401]
x: 4.566380057852584, y: 114.66910199076042, z: 203.128814011853
[  4.98107374 114.83560096 202.23421508]
x: 4.9810737425992055, y: 114.83560095565672, z: 202.23421508355065
[  4.58834979 114.66906316 203.13866689]
x: 4.5883497937767, y: 114.6690631573033, z: 203.1386668853294
[  4.11844416 114.52592709 204.00970119]
x: 4.118444160993871, y: 114.52592709130198, z: 204.0097011917081
[  4.65762135 114.66382231 203.17887458]
x: 4.657621352680783, y: 114.6638223064341, z: 203.178874575856
[  5.31168591 114.76578656 202.42933949

[ 34.98504628 118.50629303 208.14390066]
x: 34.9850462752159, y: 118.50629302537105, z: 208.14390065952261
[ 35.97378092 118.62548199 208.05335896]
x: 35.973780916582825, y: 118.62548198778214, z: 208.0533589553176
[ 36.97002693 118.7041192  208.01716419]
x: 36.970026934341625, y: 118.70411919958573, z: 208.01716419023407
[ 37.96440045 118.807138   207.9924978 ]
x: 37.96440045389438, y: 118.80713799755289, z: 207.9924977985717
[ 38.95416125 118.94217086 207.94624101]
x: 38.954161251460185, y: 118.94217085663065, z: 207.9462410091118
[ 39.94572381 119.04704536 207.87005021]
x: 39.94572380643828, y: 119.04704536141678, z: 207.8700502103816
[ 40.93108274 119.16846057 207.75035847]
x: 40.93108274337686, y: 119.1684605667402, z: 207.7503584675106
[ 41.91961801 119.30017935 207.67654668]
x: 41.91961801480511, y: 119.30017934969727, z: 207.67654668417927
[ 42.91130751 119.39474765 207.58931838]
x: 42.91130751186775, y: 119.39474765388232, z: 207.5893183788009
[ 43.9024941  119.492865   207.50

[104.42421896 127.88442213 175.48231808]
x: 104.42421896320938, y: 127.88442212859665, z: 175.48231808256799
[105.13428591 128.03037861 174.79347729]
x: 105.13428590568066, y: 128.03037860593162, z: 174.79347728533438
[105.87332523 128.16491618 174.13338598]
x: 105.87332522504695, y: 128.1649161788019, z: 174.1333859841368
[106.64685859 128.32290536 173.51963885]
x: 106.64685859123556, y: 128.32290536184314, z: 173.519638846111
[107.33209356 128.48628375 172.80987794]
x: 107.3320935594749, y: 128.48628374536418, z: 172.80987794122822
[108.07010367 128.62244391 172.14896835]
x: 108.07010366714786, y: 128.62244390718828, z: 172.14896834733165
[108.84036437 128.74854666 171.52383112]
x: 108.84036436809929, y: 128.74854665972333, z: 171.52383112369762
[109.6041882  128.88522065 170.89304323]
x: 109.60418820393642, y: 128.88522065020197, z: 170.89304322897098
[110.35399276 129.00287943 170.24192915]
x: 110.35399275582252, y: 129.0028794253484, z: 170.24192914787469
[111.09868805 129.151467 

[165.99034324 136.51922644 126.87591354]
x: 165.99034324375603, y: 136.51922643937397, z: 126.8759135403173
[166.80024097 136.60275678 126.29532044]
x: 166.80024097154367, y: 136.60275677542387, z: 126.29532043539463
[167.51735088 136.73107911 125.61027536]
x: 167.51735088175158, y: 136.7310791072311, z: 125.61027535962144
[168.2253582  136.8637449  124.91664331]
x: 168.22535820042665, y: 136.86374490487833, z: 124.91664330814376
[167.44622609 136.7511217  125.533303  ]
x: 167.44622609076384, y: 136.75112170496595, z: 125.5333029959245
[166.72159527 136.60741189 126.20728939]
x: 166.72159527053654, y: 136.60741189274742, z: 126.20728939359792
[165.95703358 136.44397184 126.83077377]
x: 165.95703357617836, y: 136.44397184362845, z: 126.83077376859389
[165.11140407 136.31119007 127.34776481]
x: 165.11140406691453, y: 136.31119006780995, z: 127.34776480630406
[164.23860373 136.16914938 127.81471664]
x: 164.23860373074032, y: 136.169149377628, z: 127.8147166405512
[163.36685428 136.0035318

[215.26036562 140.40375617 124.82931007]
x: 215.2603656241499, y: 140.40375617046504, z: 124.82931007403461
[216.25136533 140.48139795 124.72026264]
x: 216.2513653272438, y: 140.4813979452669, z: 124.72026263814827
[217.24481278 140.55559424 124.63333119]
x: 217.24481277617681, y: 140.55559424139472, z: 124.63333119476131
[218.23576001 140.64633763 124.53439076]
x: 218.2357600135169, y: 140.64633763491642, z: 124.53439076146857
[219.22705645 140.69609863 124.41250879]
x: 219.22705645149267, y: 140.69609863196288, z: 124.41250878893187
[220.21859951 140.74111876 124.29078967]
x: 220.21859951367773, y: 140.74111875698424, z: 124.29078966892314
[221.21039681 140.80421462 124.17962743]
x: 221.21039680555313, y: 140.80421462350344, z: 124.17962742957549
[222.20191384 140.86145178 124.06293178]
x: 222.2019138416099, y: 140.86145177822823, z: 124.06293177700803
[223.19599288 140.93146313 123.97983377]
x: 223.19599287909935, y: 140.9314631287544, z: 123.97983377449586
[224.1888308  141.0215308

[287.06275268 147.27745162 114.89647785]
x: 287.06275268061563, y: 147.27745162401004, z: 114.89647785372125
[286.08891286 147.10710803 115.0468742 ]
x: 286.08891285843873, y: 147.10710802908358, z: 115.04687419812471
[285.13492    147.12224679 115.34632109]
x: 285.1349199975989, y: 147.12224679239668, z: 115.34632108709158
[284.1544879  146.95407668 115.44865251]
x: 284.15448790293374, y: 146.95407667532803, z: 115.44865250687805
[283.16204757 146.88103964 115.54728198]
x: 283.1620475681619, y: 146.88103963968754, z: 115.54728198189795
[284.15418144 147.0061751  115.54389171]
x: 284.1541814418706, y: 147.00617509699862, z: 115.54389170709686
[283.18805782 146.77158614 115.65147036]
x: 283.1880578181239, y: 146.77158614296815, z: 115.65147035872143
[284.14710318 146.98420861 115.8386165 ]
x: 284.14710318023594, y: 146.9842086129386, z: 115.83861650128117
[285.1199485  147.18101813 115.96042782]
x: 285.11994850026707, y: 147.18101813040184, z: 115.96042781902023
[286.05352912 147.281273

[298.59639228 151.07955209 150.66161581]
x: 298.59639227547194, y: 151.07955208961675, z: 150.66161580867683
[298.66510711 151.18257356 151.65391861]
x: 298.6651071095427, y: 151.1825735584388, z: 151.65391860950947
[298.77455896 151.27765496 152.6433527 ]
x: 298.77455896092107, y: 151.2776549605813, z: 152.6433526998846
[298.89876379 151.38960097 153.62927422]
x: 298.89876379395383, y: 151.38960096631064, z: 153.62927422376592
[299.00415464 151.49129043 154.61849211]
x: 299.00415463604935, y: 151.49129042975989, z: 154.6184921084737
[299.07993715 151.59078243 155.61064046]
x: 299.0799371534621, y: 151.59078242732235, z: 155.6106404605237
[299.20959692 151.68209237 156.59798581]
x: 299.2095969191576, y: 151.68209236593916, z: 156.5979858105758
[299.3121759  151.79313099 157.58649377]
x: 299.31217589550516, y: 151.7931309938025, z: 157.58649376539137
[299.43804621 151.89362323 158.57343752]
x: 299.43804621046894, y: 151.8936232308722, z: 158.57343751966494
[299.55374517 152.00680239 159

[309.02426685 159.436303   227.41837879]
x: 309.0242668470566, y: 159.43630299619767, z: 227.41837879351655
[309.18001527 159.54847435 228.39978595]
x: 309.1800152746726, y: 159.5484743470496, z: 228.39978595435406
[309.4361816  159.65392174 229.36064997]
x: 309.43618159748564, y: 159.65392173562972, z: 229.36064997350454
[309.71117413 159.77641765 230.31426093]
x: 309.7111741267136, y: 159.77641764578053, z: 230.31426093236828
[309.94713732 159.87583494 231.28092404]
x: 309.9471373182467, y: 159.8758349444887, z: 231.28092404481183
[310.11925928 159.95633408 232.26270504]
x: 310.119259277882, y: 159.95633408391524, z: 232.2627050384977
[310.2468181  160.01660453 233.25270313]
x: 310.24681809923663, y: 160.0166045338568, z: 233.25270312938395
[310.70931332 160.07838437 234.13716987]
x: 310.70931331858566, y: 160.07838436891817, z: 234.13716987497645
[310.94488331 160.14010779 235.10706523]
x: 310.94488330596283, y: 160.1401077940223, z: 235.10706523007434
[311.23453569 160.26859432 236

[285.20201253 165.84829376 240.9479334 ]
x: 285.20201252655494, y: 165.84829375687428, z: 240.9479334027888
[284.38519551 166.00454543 241.50326697]
x: 284.38519550869233, y: 166.00454543203006, z: 241.5032669722234
[283.55380317 166.17728479 242.03142215]
x: 283.5538031681518, y: 166.17728479392392, z: 242.03142214728362
[282.73166068 166.33770339 242.5776342 ]
x: 282.7316606803083, y: 166.33770339221877, z: 242.5776341967696
[281.93176236 166.50914198 243.15276157]
x: 281.9317623629216, y: 166.50914198354158, z: 243.15276156635568
[281.09984824 166.66431839 243.68552716]
x: 281.09984824352426, y: 166.664318389897, z: 243.68552716289696
[280.24598614 166.81419037 244.18398267]
x: 280.24598613671077, y: 166.81419037128813, z: 244.183982669178
[279.3901862  166.95419823 244.68198294]
x: 279.39018620003765, y: 166.95419822511872, z: 244.68198293951528
[278.5408181  167.10850235 245.18672452]
x: 278.540818095704, y: 167.10850234536684, z: 245.18672451875665
[277.70872314 167.26158535 245.

[215.71203435 177.36573356 278.49458453]
x: 215.71203434909913, y: 177.3657335596835, z: 278.4945845253591
[214.89696404 177.48634333 279.06125345]
x: 214.8969640392131, y: 177.4863433290427, z: 279.0612534529326
[214.11734691 177.63786562 279.66890312]
x: 214.11734690738888, y: 177.63786561771136, z: 279.6689031248676
[213.26283841 177.72937633 280.18021616]
x: 213.262838409262, y: 177.72937632691261, z: 280.1802161569041
[212.53386539 178.00715639 280.80586508]
x: 212.53386539348057, y: 178.0071563904451, z: 280.80586508287325
[211.80099468 178.17322253 281.46565486]
x: 211.80099467721553, y: 178.17322252693543, z: 281.4656548611756
[211.0584638  178.31696439 282.11986138]
x: 211.05846380112465, y: 178.31696439050162, z: 282.119861384156
[210.20059787 178.47326453 282.60938801]
x: 210.2005978720855, y: 178.4732645306429, z: 282.6093880065021
[209.4112974  178.60836195 283.20834832]
x: 209.4112974012736, y: 178.60836194882083, z: 283.2083483176895
[208.63382566 178.78863756 283.810875

[164.04366702 186.06215917 309.48483154]
x: 164.04366702252085, y: 186.0621591698932, z: 309.4848315370543
[165.00920135 185.91886086 309.2675551 ]
x: 165.00920135247182, y: 185.9188608555887, z: 309.2675550983787
[165.99071079 185.78352824 309.13218779]
x: 165.99071078969288, y: 185.78352823862937, z: 309.13218779275104
[166.9719047  185.65999221 308.98387272]
x: 166.97190470014218, y: 185.65999221396456, z: 308.98387272033034
[167.95380363 185.51089689 308.86706061]
x: 167.95380363252147, y: 185.51089688500514, z: 308.8670606084805
[168.94101158 185.35896697 308.81871019]
x: 168.94101158262308, y: 185.35896696677688, z: 308.8187101875594
[169.9255162  185.1996096  308.74552624]
x: 169.9255161995451, y: 185.19960960266806, z: 308.74552624284837
[170.90651241 185.00654467 308.72622969]
x: 170.90651241464013, y: 185.00654466786128, z: 308.72622969089883
[171.89081308 184.8386998  308.78082178]
x: 171.89081308173044, y: 184.83869979658363, z: 308.7808217777915
[172.86913025 184.63567565 

[108.99197366 195.4945937  304.58178356]
x: 108.99197366429563, y: 195.49459369720668, z: 304.58178355759776
[108.01719712 195.67628878 304.45217803]
x: 108.01719712489975, y: 195.67628878298538, z: 304.45217802512633
[107.02746499 195.80042261 304.38131839]
x: 107.02746498684178, y: 195.80042260993588, z: 304.3813183899188
[106.03620056 195.92419598 304.33576626]
x: 106.0362005641396, y: 195.92419598328672, z: 304.33576626226034
[105.04915324 196.07334074 304.27666104]
x: 105.04915324250153, y: 196.07334073743968, z: 304.2766610412076
[104.06367451 196.19884242 304.16228887]
x: 104.0636745090316, y: 196.19884242259448, z: 304.16228887281983
[103.07932874 196.37038103 304.1218177 ]
x: 103.07932874169171, y: 196.3703810320123, z: 304.1218177003758
[102.10482123 196.50914789 303.94552569]
x: 102.10482123210883, y: 196.5091478873562, z: 303.9455256880086
[101.11742861 196.6604074  303.89887408]
x: 101.11742861087077, y: 196.66040739623813, z: 303.89887408034747
[100.13052275 196.79045691 

[103.50396321 200.01912477 329.53039113]
x: 103.50396320949382, y: 200.01912476684547, z: 329.5303911316139
[103.4477473  200.1576798  330.51914908]
x: 103.44774729548747, y: 200.15767980139645, z: 330.5191490764178
[103.38972364 200.28217781 331.50967091]
x: 103.38972363901267, y: 200.28217781081216, z: 331.50967090905993
[103.33045089 200.42593933 332.49750661]
x: 103.33045088870287, y: 200.4259393275028, z: 332.49750660764016
[103.25506069 200.58686755 333.48158914]
x: 103.25506068545761, y: 200.5868675524923, z: 333.481589136525
[103.15967468 200.72859641 334.4668883 ]
x: 103.15967468019956, y: 200.7285964088689, z: 334.4668882998612
[103.0976372  200.86763886 335.45522961]
x: 103.09763719756536, y: 200.8676388586703, z: 335.4552296113025
[103.01918513 201.00186539 336.44306994]
x: 103.01918513000413, y: 201.0018653863098, z: 336.4430699386698
[102.99418756 201.15890641 337.4303456 ]
x: 102.99418756162979, y: 201.1589064129463, z: 337.43034560307575
[102.85897975 201.29515599 338.4

[ 96.20595423 211.53065342 411.33862197]
x: 96.20595422609566, y: 211.53065341806018, z: 411.3386219705451
[ 96.10680329 211.67338416 412.3234047 ]
x: 96.10680328684758, y: 211.67338416476986, z: 412.323404700486
[ 96.08567594 211.81660195 413.31287036]
x: 96.08567594485172, y: 211.8166019507241, z: 413.3128703649769
[ 96.02897523 211.9570713  414.30133048]
x: 96.02897523327094, y: 211.95707130017718, z: 414.3013304760438
[ 95.98050057 212.10854148 415.28860298]
x: 95.98050057126711, y: 212.10854148399517, z: 415.2886029767029
[ 95.92570369 212.24863592 416.27722366]
x: 95.92570369447141, y: 212.248635921783, z: 416.27722365764896
[ 95.87779272 212.40020763 417.26450809]
x: 95.87779271762672, y: 212.40020762893403, z: 417.26450809279874
[ 95.83920658 212.54636552 418.25301656]
x: 95.83920657585611, y: 212.54636551576712, z: 418.25301655597934
[ 95.76131904 212.68602178 419.24014859]
x: 95.76131903733247, y: 212.68602178258055, z: 419.2401485929847
[ 95.68489413 212.83052851 420.2266966

[ 93.35697541 221.38029243 475.41180717]
x: 93.3569754138946, y: 221.3802924300862, z: 475.41180716510183
[ 93.34139054 221.54943469 476.39727559]
x: 93.34139053815811, y: 221.54943469211258, z: 476.3972755851158
[ 93.27863826 221.68292992 477.38633634]
x: 93.27863825887911, y: 221.68292992220353, z: 477.3863363390577
[ 93.2757342  221.8622852  478.37011642]
x: 93.2757341974051, y: 221.86228519877702, z: 478.3701164217958
[ 93.24185799 222.03065362 479.35525828]
x: 93.24185799256739, y: 222.0306536245794, z: 479.3552582775397
[ 93.06191018 222.21977833 480.32058238]
x: 93.06191018448956, y: 222.21977833068158, z: 480.3205823847232
[ 92.99532579 222.40891658 481.30027276]
x: 92.99532578850142, y: 222.40891658258587, z: 481.30027276432145
[ 92.94748508 222.58559315 482.28337838]
x: 92.94748508211849, y: 222.58559315204417, z: 482.2833783825625
[ 92.88430414 222.72491785 483.2716075 ]
x: 92.88430413689004, y: 222.7249178482702, z: 483.2716075043665
[ 92.81836342 222.86649405 484.25933621]

[119.46244423 236.34897051 530.49340688]
x: 119.46244423449022, y: 236.3489705088275, z: 530.493406875295
[120.43410305 236.58275093 530.52841906]
x: 120.43410305317089, y: 236.5827509335226, z: 530.5284190604511
[121.4027347  236.83104353 530.53859373]
x: 121.40273469675793, y: 236.83104353347355, z: 530.5385937275892
[122.37467105 237.06053724 530.59028871]
x: 122.37467104717894, y: 237.0605372367782, z: 530.5902887067821
[123.34554661 237.28896595 530.66254494]
x: 123.34554661081276, y: 237.28896594914997, z: 530.6625449404424
[124.31570158 237.51961722 530.73737357]
x: 124.31570158277847, y: 237.51961721514442, z: 530.7373735704264
[125.28561551 237.75597224 530.79571126]
x: 125.28561550561996, y: 237.75597223797575, z: 530.7957112551641
[126.26253748 237.96942217 530.80362202]
x: 126.26253748130513, y: 237.96942216942176, z: 530.8036220192869
[127.23955914 238.18256196 530.80395369]
x: 127.23955913903735, y: 238.18256195998075, z: 530.8039536856168
[128.21362766 238.39266315 530.8

[194.20983331 252.69275525 537.53484927]
x: 194.20983330799606, y: 252.69275525473412, z: 537.5348492668963
[195.15171091 252.92512598 537.77748154]
x: 195.15171091355907, y: 252.9251259803744, z: 537.7774815442302
[196.09872124 253.13482684 538.02078588]
x: 196.0987212358033, y: 253.13482684335332, z: 538.0207858755289
[197.05055936 253.3436785  538.24525227]
x: 197.05055936409175, y: 253.34367849960014, z: 538.245252272166
[197.99252921 253.58077024 538.48290815]
x: 197.99252920820572, y: 253.58077024348134, z: 538.4829081531435
[198.91180314 253.8008647  538.80924213]
x: 198.91180314317404, y: 253.80086469746982, z: 538.8092421290199
[199.82554567 254.02127918 539.15055144]
x: 199.82554567479954, y: 254.0212791761521, z: 539.1505514366659
[200.73767221 254.25017081 539.49060114]
x: 200.73767221293164, y: 254.25017080568497, z: 539.4906011394519
[201.63699245 254.46658225 539.87058692]
x: 201.63699245450238, y: 254.46658224522236, z: 539.8705869180521
[202.55191441 254.6895694  540.2

[262.71983692 269.45189922 559.81660533]
x: 262.71983692168664, y: 269.4518992157869, z: 559.8166053330957
[263.44400618 269.65892779 559.15879225]
x: 263.44400617982683, y: 269.6589277901721, z: 559.1587922479775
[264.15711772 269.87332093 558.49132876]
x: 264.1571177248133, y: 269.87332093408406, z: 558.4913287626463
[264.87765228 270.0984382  557.8354689 ]
x: 264.877652284928, y: 270.09843819638064, z: 557.8354688950706
[265.52438422 270.3062997  557.10162191]
x: 265.52438422069656, y: 270.30629970350117, z: 557.1016219102606
[266.20370433 270.531908   556.40332033]
x: 266.2037043279967, y: 270.53190799531376, z: 556.4033203346623
[266.82168689 270.74242862 555.64583857]
x: 266.8216868880681, y: 270.7424286184313, z: 555.6458385707302
[267.47219611 270.96425864 554.91945768]
x: 267.4721961070092, y: 270.96425863700597, z: 554.9194576796465
[268.09875825 271.17458658 554.16900312]
x: 268.0987582450432, y: 271.1745865764604, z: 554.1690031206844
[268.73970296 271.39460708 553.43362509

[312.01786291 285.39679604 501.59110597]
x: 312.01786290564445, y: 285.3967960390608, z: 501.59110596864326
[312.66005617 285.58020695 500.84682897]
x: 312.6600561676065, y: 285.5802069462316, z: 500.8468289681783
[313.29473452 285.79335189 500.10402844]
x: 313.2947345227867, y: 285.7933518861361, z: 500.1040284430985
[313.93011461 285.96408166 499.35093915]
x: 313.93011461398356, y: 285.96408166460225, z: 499.35093915061356
[314.52909358 286.14880909 498.57177295]
x: 314.5290935840688, y: 286.1488090926947, z: 498.57177294837817
[315.14790017 286.33289424 497.80810348]
x: 315.1479001717195, y: 286.3328942436377, z: 497.8081034751882
[315.77266467 286.51550709 497.04894482]
x: 315.7726646700357, y: 286.5155070888275, z: 497.04894481560814
[316.42463581 286.69239285 496.31162192]
x: 316.4246358116648, y: 286.6923928491888, z: 496.3116219160152
[317.06454809 286.87427787 495.56500949]
x: 317.0645480851124, y: 286.87427787456767, z: 495.56500948654866
[317.72195797 287.0638141  494.835702

[281.05517167 299.34867428 459.01212255]
x: 281.0551716712374, y: 299.34867427708326, z: 459.0121225490648
[280.07481233 299.49691651 458.88204643]
x: 280.07481232650775, y: 299.49691650999273, z: 458.8820464344889
[279.09519232 299.65649717 458.76006833]
x: 279.09519232111126, y: 299.65649717376084, z: 458.7600683349045
[278.10956535 299.81562861 458.70335269]
x: 278.1095653528416, y: 299.8156286137938, z: 458.70335269144897
[277.11883366 299.95081834 458.69014456]
x: 277.1188336619557, y: 299.9508183391627, z: 458.6901445564973
[276.13066785 300.08965245 458.62492637]
x: 276.13066784736566, y: 300.0896524517296, z: 458.62492636836447
[275.14670183 300.2514986  458.54998176]
x: 275.1467018269105, y: 300.2514986002328, z: 458.549981756789
[274.15937958 300.40527633 458.51064746]
x: 274.1593795788772, y: 300.4052763337525, z: 458.51064745608437
[273.17081117 300.54355893 458.45056064]
x: 273.1708111707409, y: 300.54355893109874, z: 458.45056063801314
[272.18556757 300.70113932 458.38375

[221.72077647 308.66121945 444.06240999]
x: 221.72077647464167, y: 308.66121944972963, z: 444.0624099930399
[221.6060262  308.76734938 443.07470112]
x: 221.60602619859486, y: 308.7673493759913, z: 443.0747011225225
[221.49204933 308.89327291 442.0892304 ]
x: 221.49204932602635, y: 308.8932729072729, z: 442.0892304041402
[221.43971439 309.02013774 441.09869198]
x: 221.43971439130655, y: 309.02013773699326, z: 441.0986919800557
[221.400718   309.14186999 440.10689536]
x: 221.40071799895546, y: 309.1418699867753, z: 440.10689535738226
[221.34526782 309.26001202 439.11544806]
x: 221.3452678213061, y: 309.2600120235031, z: 439.1154480632933
[221.31966429 309.37329169 438.12221487]
x: 221.31966428626126, y: 309.3732916885094, z: 438.12221486988443
[221.29456123 309.46922754 437.12714394]
x: 221.29456123287002, y: 309.46922754039025, z: 437.12714394324945
[221.28959995 309.58202167 436.13353795]
x: 221.2895999483715, y: 309.58202167094714, z: 436.13353795002683
[221.30896392 309.68239328 435.

[226.10662036 319.01221199 365.97178608]
x: 226.10662035805453, y: 319.01221198612603, z: 365.9717860771589
[226.19364881 319.15653256 364.98608956]
x: 226.19364881321746, y: 319.1565325564959, z: 364.9860895615112
[226.28848396 319.31341109 364.00303543]
x: 226.28848395650073, y: 319.313411087267, z: 364.00303543167837
[226.3431161  319.44208471 363.01285442]
x: 226.3431160972228, y: 319.44208470735174, z: 363.0128544236327
[226.44064485 319.58722136 362.02826136]
x: 226.44064485191058, y: 319.58722136316584, z: 362.02826136396385
[226.48911942 319.69466416 361.03523253]
x: 226.48911942409387, y: 319.6946641603018, z: 361.0352325319579
[226.57597822 319.81414486 360.04620275]
x: 226.57597822484001, y: 319.81414485887603, z: 360.04620274908933
[226.66175574 319.95148877 359.0594004 ]
x: 226.66175574389965, y: 319.9514887698397, z: 359.0594004044706
[226.75555851 320.08547491 358.0728667 ]
x: 226.75555850570765, y: 320.0854749086665, z: 358.0728666967447
[226.82996493 320.23630434 357.0

[229.94796579 329.46344993 290.09889871]
x: 229.94796578876947, y: 329.4634499339711, z: 290.09889870984523
[229.5510542  329.65131626 289.20047373]
x: 229.55105420492637, y: 329.6513162573653, z: 289.2004737329298
[229.1133172  329.86035671 288.32600909]
x: 229.11331720404826, y: 329.8603567077424, z: 288.32600909203904
[228.59559532 330.04665881 287.49099078]
x: 228.59559531528046, y: 330.0466588056147, z: 287.4909907843242
[228.10885329 330.19748105 286.63056365]
x: 228.1088532900433, y: 330.19748105078526, z: 286.6305636513085
[227.67280696 330.34159168 285.74225305]
x: 227.6728069626947, y: 330.34159167996427, z: 285.74225304855554
[227.05754373 330.54901253 284.98170868]
x: 227.05754372759702, y: 330.54901252872156, z: 284.9817086757292
[226.40257527 330.68832902 284.23900602]
x: 226.40257526583653, y: 330.68832902359156, z: 284.2390060243564
[225.84590558 330.88228902 283.43123231]
x: 225.84590557795735, y: 330.8822890246766, z: 283.4312323081614
[225.19624119 330.99074282 282.6

[159.71763119 340.17558207 272.72237825]
x: 159.71763118739327, y: 340.1755820652229, z: 272.7223782453522
[158.73082156 340.30535867 272.62560642]
x: 158.7308215569574, y: 340.30535867180436, z: 272.62560642268085
[157.73632858 340.39223366 272.56698519]
x: 157.73632857680195, y: 340.3922336600145, z: 272.566985190649
[156.75063354 340.54563213 272.49716976]
x: 156.75063353519934, y: 340.5456321320987, z: 272.49716976454437
[155.76398591 340.6647543  272.38610052]
x: 155.763985912162, y: 340.6647542957969, z: 272.3861005155573
[154.77438835 340.76621    272.28410345]
x: 154.77438834770928, y: 340.7662099984195, z: 272.28410345268543
[153.78205625 340.86166847 272.20558787]
x: 153.78205625411098, y: 340.8616684689861, z: 272.2055878719909
[152.78976323 340.95113252 272.11985148]
x: 152.7897632255451, y: 340.9511325243171, z: 272.11985148378164
[151.80417377 341.07261913 272.00214661]
x: 151.8041737730158, y: 341.07261912686823, z: 272.00214661360434
[150.81371843 341.21004751 271.99158

[153.12767411 341.87087885 281.39961596]
x: 153.12767411203902, y: 341.8708788528873, z: 281.3996159576005
[152.19563074 342.06927631 281.70282149]
x: 152.19563073598493, y: 342.0692763077774, z: 281.7028214902788
[151.27369147 342.23569603 282.05258208]
x: 151.27369147189637, y: 342.2356960293826, z: 282.05258207924294
[150.32254476 342.38902979 282.32055353]
x: 150.3225447637452, y: 342.38902978877803, z: 282.32055352884674
[149.35208585 342.5556864  282.49501   ]
x: 149.35208584610362, y: 342.55568640430164, z: 282.4950100038542
[148.36888476 342.69647087 282.61117949]
x: 148.36888475523565, y: 342.6964708682283, z: 282.6111794905227
[147.38212402 342.84059226 282.68555878]
x: 147.38212402201177, y: 342.8405922622152, z: 282.6855587830888
[146.39123154 342.97518102 282.68132024]
x: 146.39123154454805, y: 342.97518101669914, z: 282.6813202370937
[145.40136733 343.07721377 282.58253685]
x: 145.40136733167301, y: 343.0772137652295, z: 282.5825368463008
[144.41394542 343.23531366 282.58

[ 74.63569352 355.51669342 280.24140167]
x: 74.63569351568616, y: 355.51669342187006, z: 280.241401665162
[ 75.59640086 355.33043717 280.44719284]
x: 75.59640085939198, y: 355.33043717165316, z: 280.44719284331296
[ 76.57973332 355.15240875 280.48411378]
x: 76.57973331799144, y: 355.1524087459678, z: 280.48411377927914
[ 77.56296421 354.98673103 280.56032338]
x: 77.56296421293874, y: 354.9867310326715, z: 280.56032337538056
[ 78.5515349  354.84163361 280.60124697]
x: 78.55153489683364, y: 354.84163360973673, z: 280.6012469724995
[ 79.53172896 354.65850046 280.5258689 ]
x: 79.53172895649513, y: 354.658500456431, z: 280.52586890165304
[ 80.47668201 354.34704911 280.4255605 ]
x: 80.47668201469554, y: 354.3470491076277, z: 280.4255605015751
[ 81.45680626 354.15481532 280.37654386]
x: 81.45680626064613, y: 354.15481531507453, z: 280.3765438564399
[ 82.34021042 353.87633175 279.9996566 ]
x: 82.3402104159391, y: 353.8763317516086, z: 279.9996566010301
[ 83.25494448 353.61083205 279.69507247]


[102.14116732 352.31841473 286.85039272]
x: 102.14116731603528, y: 352.31841472930074, z: 286.85039271733893
[102.1014708  352.45645468 287.84002354]
x: 102.10147079975035, y: 352.4564546802548, z: 287.84002353665255
[102.06083724 352.58602765 288.83076051]
x: 102.0608372423422, y: 352.5860276477226, z: 288.8307605149237
[101.99143011 352.72787403 289.81821292]
x: 101.99143010621634, y: 352.7278740304716, z: 289.8182129204379
[101.93041162 352.89506308 290.80224776]
x: 101.93041162015575, y: 352.8950630807406, z: 290.80224776018133
[101.85593662 353.04158066 291.78864832]
x: 101.8559366200649, y: 353.04158065735226, z: 291.78864832491416
[101.77444472 353.20724493 292.77145778]
x: 101.77444471751456, y: 353.20724492637794, z: 292.7714577773447
[101.72867171 353.36918184 293.75719672]
x: 101.72867171470092, y: 353.36918183580354, z: 293.757196723303
[101.67544658 353.51565726 294.74497809]
x: 101.67544657618073, y: 353.51565725578337, z: 294.7449780938356
[101.56536758 353.63529384 295.

[ 98.52018927 362.35306631 352.95457918]
x: 98.52018927056399, y: 362.3530663111179, z: 352.95457917985283
[ 98.59506159 362.24440292 351.96332422]
x: 98.59506159270198, y: 362.2444029241351, z: 351.96332421582645
[ 98.64266708 362.09339677 350.97593834]
x: 98.64266707545379, y: 362.0933967681714, z: 350.97593834451123
[ 98.78473167 361.98312573 349.99224228]
x: 98.78473166512391, y: 361.983125730786, z: 349.9922422783019
[ 99.04088356 361.87181351 349.03203616]
x: 99.04088355872351, y: 361.87181351096604, z: 349.0320361560948
[ 99.39896331 361.71421272 348.11174225]
x: 99.3989633143138, y: 361.71421271565004, z: 348.11174224763295
[ 99.59494086 361.52124799 347.15030717]
x: 99.5949408614883, y: 361.52124799062346, z: 347.1503071661538
[100.02049769 361.35516204 346.26074725]
x: 100.02049769015025, y: 361.3551620404651, z: 346.26074725094907
[100.53853665 361.18839338 345.42180515]
x: 100.53853664643093, y: 361.1883933827768, z: 345.42180514651733
[100.98486359 361.08856249 344.5325211

[ 64.78326833 371.01843261 336.49177833]
x: 64.78326833460561, y: 371.0184326087646, z: 336.49177833019746
[ 63.82267041 371.28390446 336.40945987]
x: 63.82267041385839, y: 371.2839044635171, z: 336.40945986938647
[ 62.86162843 371.55928342 336.43322391]
x: 62.86162842566342, y: 371.559283415727, z: 336.43322390957184
[ 61.89770587 371.82546623 336.43337235]
x: 61.897705873847435, y: 371.82546623272884, z: 336.4333723462183
[ 60.93469318 372.0893674  336.37894144]
x: 60.93469317863395, y: 372.0893673990758, z: 336.3789414426958
[ 59.96798423 372.339843   336.32663669]
x: 59.967984232947344, y: 372.3398430010547, z: 336.3266366901135
[ 59.00989049 372.59698274 336.20040067]
x: 59.00989048912482, y: 372.59698273866854, z: 336.2004006675687
[ 58.05101205 372.88056927 336.21183794]
x: 58.05101204549184, y: 372.8805692670218, z: 336.21183794313583
[ 57.08370604 373.11628979 336.1182702 ]
x: 57.083706038094725, y: 373.116289791091, z: 336.1182701998377
[ 56.11803698 373.37595383 336.11066362

[  4.21702319 387.65150605 333.0572845 ]
x: 4.2170231879830995, y: 387.65150605095863, z: 333.05728450401847
[  3.25466812 387.90960377 332.97208894]
x: 3.2546681170543645, y: 387.9096037710644, z: 332.9720889387944
[  2.28932127 388.16091716 332.90175371]
x: 2.2893212693563836, y: 388.1609171604021, z: 332.90175371306043
[  1.32531333 388.40754626 332.80244217]
x: 1.3253133301336009, y: 388.4075462557175, z: 332.8024421706334
[3.58493847e-01 3.88649789e+02 3.32721333e+02]
x: 0.35849384733610734, y: 388.6497887516877, z: 332.7213332264337
[ -0.60752478 388.8801236  332.6040563 ]
x: -0.6075247765727066, y: 388.88012359658273, z: 332.60405629993755
[ -1.57322944 389.1250216  332.51780394]
x: -1.5732294406929197, y: 389.12502159868467, z: 332.51780393612745
[ -2.53770495 389.3627977  332.40269741]
x: -2.5377049525521267, y: 389.36279770007354, z: 332.4026974088056
[ -3.49742264 389.62055226 332.29087372]
x: -3.497422643891556, y: 389.62055226455544, z: 332.2908737198182
[ -4.45904811 389.

[-72.76390626 407.98140072 332.9319863 ]
x: -72.76390626145765, y: 407.98140072196543, z: 332.931986296987
[-73.73145127 408.22189452 333.00957102]
x: -73.73145126930592, y: 408.2218945224944, z: 333.0095710228994
[-74.68781228 408.43797535 333.2062502 ]
x: -74.68781227657293, y: 408.43797535157887, z: 333.20625020095673
[-75.65457996 408.68102275 333.28554837]
x: -75.65457996482787, y: 408.6810227496429, z: 333.2855483676465
[-74.68611473 408.4606295  333.16935068]
x: -74.68611472953398, y: 408.4606294968993, z: 333.16935068190315
[-73.71660888 408.22299225 333.10945952]
x: -73.71660888309452, y: 408.2229922474409, z: 333.10945951903705
[-72.75195151 408.00411567 332.96273121]
x: -72.75195151003501, y: 408.004115668145, z: 332.96273121352806
[-71.80888472 407.7625006  332.73415479]
x: -71.80888471579132, y: 407.76250059926554, z: 332.7341547928605
[-70.89495097 407.48683667 332.43627141]
x: -70.89495097417169, y: 407.48683666540484, z: 332.43627140712465
[-69.92104512 407.26386654 332

[-63.04741941 407.19352312 335.15229996]
x: -63.04741941091944, y: 407.1935231204784, z: 335.1522999608245
[-63.14549845 407.4540578  334.19183019]
x: -63.1454984468692, y: 407.4540578006493, z: 334.1918301887154
[-63.23693733 407.72494733 333.2335725 ]
x: -63.236937327690235, y: 407.72494733114684, z: 333.23357250242174
[-63.29637465 407.99120475 332.27150484]
x: -63.29637464826323, y: 407.99120474718006, z: 332.2715048367504
[-63.3209581  408.23765706 331.30266176]
x: -63.320958096012674, y: 408.2376570623337, z: 331.30266175840796
[-63.3430632  408.49783381 330.33735381]
x: -63.34306319916285, y: 408.4978338071348, z: 330.3373538148587
[-63.33225077 408.74993303 329.36971283]
x: -63.332250773703414, y: 408.7499330291164, z: 329.36971283095414
[-63.34691132 409.00997928 328.40422797]
x: -63.34691132457576, y: 409.0099792765661, z: 328.4042279696356
[-63.37892093 409.27492958 327.44049734]
x: -63.37892092704264, y: 409.274929581561, z: 327.44049734273153
[-63.38850541 409.53531716 326

[-56.49537965 425.54543723 260.96792471]
x: -56.495379654904895, y: 425.5454372346979, z: 260.9679247054743
[-56.26656065 425.78427767 260.02421018]
x: -56.26656064930624, y: 425.7842776706465, z: 260.0242101782826
[-56.02769905 426.0089675  259.07950937]
x: -56.02769905022648, y: 426.00896750392013, z: 259.0795093709852
[-55.80250019 426.22320139 258.12904143]
x: -55.80250018819672, y: 426.22320138901887, z: 258.12904142569937
[-55.5631594  426.44715955 257.18428816]
x: -55.56315939695558, y: 426.4471595500654, z: 257.1842881628055
[-55.31741362 426.6868453  256.24505456]
x: -55.31741362228146, y: 426.6868452950033, z: 256.24505456145636
[-55.04755422 426.90371944 255.30689599]
x: -55.047554220279466, y: 426.9037194433738, z: 255.30689598908197
[-54.76731639 427.13543325 254.37535132]
x: -54.76731638602133, y: 427.1354332512728, z: 254.37535132161875
[-54.48888719 427.35238544 253.43971842]
x: -54.48888719257367, y: 427.35238543577583, z: 253.43971841610755
[-54.20514778 427.57812785 

[-26.81239214 442.32231154 192.2755945 ]
x: -26.81239214178149, y: 442.32231154299524, z: 192.2755945034602
[-26.29093719 442.53568142 191.4494238 ]
x: -26.290937193374297, y: 442.5356814233748, z: 191.44942380019828
[-25.76967538 442.74861178 190.62301785]
x: -25.769675380618857, y: 442.7486117758916, z: 190.62301785422508
[-25.22790512 442.9505287  189.80710454]
x: -25.227905124750844, y: 442.95052870368744, z: 189.80710453522232
[-24.70012586 443.16474642 188.98518007]
x: -24.700125864997606, y: 443.16474641626223, z: 188.9851800711787
[-24.1817972  443.38427628 188.158656  ]
x: -24.18179720021529, y: 443.3842762843739, z: 188.15865600481902
[-23.63679252 443.59479811 187.34708317]
x: -23.636792521028188, y: 443.5947981094488, z: 187.34708317331763
[-23.09089967 443.7943822  186.53334662]
x: -23.090899667850426, y: 443.7943821997382, z: 186.5333466165914
[-22.5475011  444.01130641 185.72238306]
x: -22.547501104093435, y: 444.01130640533967, z: 185.72238306011621
[-21.99862726 444.22

[ 23.57540097 458.26847462 135.3692284 ]
x: 23.57540097382951, y: 458.2684746157396, z: 135.36922840458192
[ 24.34039437 458.46068935 134.75454263]
x: 24.340394366331395, y: 458.46068934628454, z: 134.75454262567544
[ 25.11319396 458.64970486 134.14869287]
x: 25.11319395860039, y: 458.6497048643815, z: 134.14869287193505
[ 25.87065406 458.84961661 133.52717095]
x: 25.870654055980815, y: 458.84961660734604, z: 133.5271709528516
[ 26.64060375 459.03616946 132.91694517]
x: 26.640603748026635, y: 459.03616946295807, z: 132.91694517186443
[ 27.41109624 459.22279204 132.30742624]
x: 27.411096244491894, y: 459.22279203589574, z: 132.3074262401152
[ 28.17966677 459.40625589 131.69453117]
x: 28.179666767738873, y: 459.40625588659776, z: 131.69453117056307
[ 28.94551802 459.5793334  131.07524446]
x: 28.945518021048006, y: 459.5793334045121, z: 131.07524445942087
[ 29.72049659 459.76219538 130.47029015]
x: 29.720496590163183, y: 459.76219537820094, z: 130.4702901504101
[ 30.4936067  459.94316497 

[ 83.21054255 473.10590734  87.35152599]
x: 83.21054255497685, y: 473.1059073434147, z: 87.35152599214832
[ 83.97842139 473.2980531   86.74042689]
x: 83.97842138662125, y: 473.29805309589483, z: 86.7404268923976
[ 84.731615   473.49706561  86.11345528]
x: 84.73161499722912, y: 473.4970656123201, z: 86.11345527960685
[ 85.48432306 473.70676434  85.48939037]
x: 85.48432306198949, y: 473.70676433750043, z: 85.48939036799725
[ 86.24615333 473.91105325  84.87467037]
x: 86.24615333454508, y: 473.9110532451597, z: 84.87467036830218
[ 86.99585731 474.121666    84.24730587]
x: 86.99585731054064, y: 474.12166600065285, z: 84.24730586850968
[ 87.7624983  474.32236031  83.63740147]
x: 87.76249830481358, y: 474.3223603072374, z: 83.63740146517696
[ 88.53178656 474.5083608   83.02617369]
x: 88.5317865609826, y: 474.5083607989257, z: 83.02617368765699
[ 89.29604831 474.69333369  82.40836384]
x: 89.2960483100731, y: 474.6933336891408, z: 82.40836383927122
[ 90.05758903 474.88036202  81.78781881]
x: 90

[145.73744772 487.56002283  42.29513795]
x: 145.737447723262, y: 487.5600228313538, z: 42.295137946083486
[146.72478544 487.69121626  42.20596102]
x: 146.724785436201, y: 487.69121626436913, z: 42.205961022264084
[147.71221608 487.83990875  42.15237673]
x: 147.7122160765503, y: 487.83990874744916, z: 42.15237673375786
[148.70602203 487.94500971  42.18848104]
x: 148.7060220264918, y: 487.94500971327074, z: 42.18848103882102
[149.6970197  488.0420383   42.28072565]
x: 149.69701969821617, y: 488.0420382968186, z: 42.28072565173409
[150.67649975 488.18079104  42.42689851]
x: 150.67649974989394, y: 488.1807910423906, z: 42.42689850817954
[151.65395346 488.31172621  42.59254943]
x: 151.65395345941556, y: 488.3117262125248, z: 42.59254942717556
[152.61995937 488.45106065  42.8103073 ]
x: 152.61995937211398, y: 488.45106065405474, z: 42.810307297378
[153.56836199 488.56790825  43.10505993]
x: 153.56836199156584, y: 488.5679082465763, z: 43.10505992508239
[154.50409794 488.69929553  43.43237569

[203.98044015 497.787863    87.45465819]
x: 203.9804401469613, y: 497.7878629975569, z: 87.45465819405406
[204.10522249 497.98622766  88.42681087]
x: 204.10522248969784, y: 497.98622765995634, z: 88.42681087118467
[204.22568706 498.19124828  89.3981269 ]
x: 204.22568705747682, y: 498.1912482752701, z: 89.3981269037951
[204.27660551 498.40271102  90.37418572]
x: 204.27660550841435, y: 498.4027110195751, z: 90.37418572329574
[204.26614732 498.57006881  91.36002648]
x: 204.26614731650096, y: 498.570068813921, z: 91.36002647863782
[204.28460128 498.75958884  92.3417299 ]
x: 204.28460128469695, y: 498.7595888413526, z: 92.3417299013985
[204.24797306 498.93388854  93.32574107]
x: 204.24797305561992, y: 498.93388853879, z: 93.32574107425569
[204.19395168 499.11394949  94.30791201]
x: 204.19395168020807, y: 499.11394949468036, z: 94.30791200803571
[204.1125467  499.2829222   95.29016526]
x: 204.1125467031536, y: 499.28292220080647, z: 95.29016526168013
[204.03144086 499.46454015  96.27018402]


[195.83154931 512.30055832 162.52253298]
x: 195.83154930541193, y: 512.3005583241934, z: 162.52253297907075
[195.73302778 512.47349186 163.5025266 ]
x: 195.7330277786278, y: 512.4734918613701, z: 163.50252660174363
[195.58952401 512.64282459 164.47758203]
x: 195.58952401286487, y: 512.642824585498, z: 164.477582034912
[195.47948366 512.84009174 165.45173643]
x: 195.47948365646508, y: 512.8400917355913, z: 165.45173643307348
[195.37685305 513.03128224 166.42790914]
x: 195.37685304884178, y: 513.0312822357041, z: 166.42790913861555
[195.25535104 513.23734524 167.39887531]
x: 195.2553510393257, y: 513.2373452423292, z: 167.39887530640104
[195.11895656 513.42010665 168.37252556]
x: 195.11895655767464, y: 513.4201066502338, z: 168.3725255583682
[195.02991155 513.60954009 169.35037317]
x: 195.02991155097195, y: 513.609540086545, z: 169.35037317430258
[194.91185228 513.7818806  170.32831016]
x: 194.91185228169596, y: 513.7818806034932, z: 170.32831016366126
[194.80500668 513.97444923 171.3037